/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.paypal;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiLifecycle.OnActivityResultEvent;
import org.appcelerator.titanium.util.TiConvert;
import org.json.JSONException;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;

import android.net.Uri;

import com.paypal.android.sdk.payments.PayPalAuthorization;
import com.paypal.android.sdk.payments.PayPalConfiguration;
import com.paypal.android.sdk.payments.PayPalFuturePaymentActivity;
import com.paypal.android.sdk.payments.PayPalItem;
import com.paypal.android.sdk.payments.PayPalPayment;
import com.paypal.android.sdk.payments.PayPalPaymentDetails;
import com.paypal.android.sdk.payments.PayPalProfileSharingActivity;
import com.paypal.android.sdk.payments.PayPalService;
import com.paypal.android.sdk.payments.PaymentActivity;
import com.paypal.android.sdk.payments.PaymentConfirmation;

// examle : http://stackoverflow.com/questions/7631841/how-integrate-paypal-in-android-application

@Kroll.proxy(creatableInModule = PaypalModule.class)
public class PaymentProxy extends KrollProxy implements OnActivityResultEvent {
	// Standard Debugging variables
	private static final String LCAT = "PaymentProxy";
	String currencyCode;
	String shortDescription;

	String clientId;
	int intentMode;
	boolean futurePayment = false;
	BigDecimal amount, shipping, tax;
	KrollModule proxy; // for event firing
	private static final int REQUEST_CODE_PAYMENT = 1,
			REQUEST_CODE_FUTUREPAYMENT = 2, REQUEST_CODE_PROFILESHARING = 3;
	PayPalConfiguration ppConfiguration = new PayPalConfiguration();
	List<KrollDict> paymentItems = null;

	public PaymentProxy() {
		super();
	}

	@Override
	public void onActivityResult(Activity act, int REQUEST_CODE, int resCode,
			Intent data) {
		// error: method does not override or implement a method from a
		// supertype
		Log.d(LCAT, ">>>>>>>>>>  Answer from PayPal: REQUEST_CODE="
				+ REQUEST_CODE + "   resCode=" + resCode);
		if (REQUEST_CODE == REQUEST_CODE_PAYMENT) {
			if (resCode == Activity.RESULT_OK) {
				PaymentConfirmation confirm = data
						.getParcelableExtra(PaymentActivity.EXTRA_RESULT_CONFIRMATION);
				if (confirm != null) {
					try {
						if (proxy.hasListeners("paymentDidComplete")) {
							KrollDict event = new KrollDict();
							event.put("success", true);
							event.put("confirm", confirm.toJSONObject()
									.toString(4));
							event.put("payment", confirm.getPayment()
									.toJSONObject());
							proxy.fireEvent("paymentDidComplete", event);
						}

					} catch (JSONException e) {
						Log.e(LCAT, "an extremely unlikely failure occurred: ",
								e);
					}
				}
			} else if (resCode == Activity.RESULT_CANCELED) {
				if (proxy.hasListeners("paymentDidCancel")) {
					KrollDict event = new KrollDict();
					event.put("success", false);
					proxy.fireEvent("paymentDidCancel", event);
				}
			} else if (resCode == PaymentActivity.RESULT_EXTRAS_INVALID) {
			}
		} else if (REQUEST_CODE == REQUEST_CODE_FUTUREPAYMENT) {
			if (resCode == Activity.RESULT_OK) {
				PayPalAuthorization auth = data
						.getParcelableExtra(PayPalFuturePaymentActivity.EXTRA_RESULT_AUTHORIZATION);
				if (auth != null) {
					try {
						Log.i("FuturePaymentExample", auth.toJSONObject()
								.toString(4));

						String authorization_code = auth.getAuthorizationCode();
						Log.i("FuturePaymentExample", authorization_code);

						sendAuthorizationToServer(auth);
						// displayResultText("Future Payment code received from PayPal");

					} catch (JSONException e) {
						Log.e("FuturePaymentExample",
								"an extremely unlikely failure occurred: ", e);
					}
				}
			} else if (resCode == Activity.RESULT_CANCELED) {
				Log.i("FuturePaymentExample", "The user canceled.");
				if (proxy.hasListeners("paymentDidCancel")) {
					KrollDict event = new KrollDict();
					event.put("success", false);
					proxy.fireEvent("paymentDidCancel", event);
				}
			} else if (resCode == PayPalFuturePaymentActivity.RESULT_EXTRAS_INVALID) {
				Log.i("FuturePaymentExample",
						"Probably the attempt to previously start the PayPalService had an invalid PayPalConfiguration. Please see the docs.");
			}
		} else if (REQUEST_CODE == REQUEST_CODE_PROFILESHARING) {
			if (resCode == Activity.RESULT_OK) {
				PayPalAuthorization auth = data
						.getParcelableExtra(PayPalProfileSharingActivity.EXTRA_RESULT_AUTHORIZATION);
				if (auth != null) {
					try {
						Log.i("ProfileSharingExample", auth.toJSONObject()
								.toString(4));

						String authorization_code = auth.getAuthorizationCode();
						Log.i("ProfileSharingExample", authorization_code);

						sendAuthorizationToServer(auth);
						// displayResultText("Profile Sharing code received from PayPal");

					} catch (JSONException e) {
						Log.e("ProfileSharingExample",
								"an extremely unlikely failure occurred: ", e);
					}
				}
			} else if (resCode == Activity.RESULT_CANCELED) {
				if (proxy.hasListeners("paymentDidCancel")) {
					KrollDict event = new KrollDict();
					event.put("success", false);
					proxy.fireEvent("paymentDidCancel", event);
				}
				Log.i("ProfileSharingExample", "The user canceled.");
			} else if (resCode == PayPalFuturePaymentActivity.RESULT_EXTRAS_INVALID) {
				Log.i("ProfileSharingExample",
						"Probably the attempt to previously start the PayPalService had an invalid PayPalConfiguration. Please see the docs.");
			}
		}

	}

	/*
	 * this method (called by JS level) opens the billing layer
	 */
	@Kroll.method
	public void show() {
		Context context = TiApplication.getInstance().getApplicationContext();
		Intent intent = new Intent(context, PaymentActivity.class);
		if (futurePayment == false) {
			PayPalPayment thingsToBuy = null;
			if (intentMode == PaypalModule.PAYMENT_INTENT_SALE) {
				thingsToBuy = getStuffToBuy(PayPalPayment.PAYMENT_INTENT_SALE);
			} else if (intentMode == PaypalModule.PAYMENT_INTENT_AUTHORIZE) {
				thingsToBuy = getStuffToBuy(PayPalPayment.PAYMENT_INTENT_AUTHORIZE);
			} else if (intentMode == PaypalModule.PAYMENT_INTENT_ORDER) {
				thingsToBuy = getStuffToBuy(PayPalPayment.PAYMENT_INTENT_ORDER);
			}

			/* putting configuration */
			intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION,
					ppConfiguration);
			/* putting payload */
			intent.putExtra(PaymentActivity.EXTRA_PAYMENT, thingsToBuy);
			/* start the overlay */
			TiApplication.getAppRootOrCurrentActivity().startActivityForResult(
					intent, REQUEST_CODE_PAYMENT);
		} else {
			intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION,
					ppConfiguration);
			TiApplication.getAppRootOrCurrentActivity().startActivityForResult(
					intent, REQUEST_CODE_FUTUREPAYMENT);
		}

	}

	@SuppressWarnings("unchecked")
	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);
		if (options.containsKeyAndNotNull("intent")) {
			this.intentMode = TiConvert.toInt(options.get("intent"));
		}
		if (options.containsKeyAndNotNull("futurePayment")) {
			this.futurePayment = TiConvert.toBoolean(options
					.get("futurePayment"));
		}
		if (options.containsKeyAndNotNull("currencyCode")) {
			this.currencyCode = TiConvert.toString(options.get("currencyCode"));
		}
		if (options.containsKeyAndNotNull("shortDescription")) {
			this.shortDescription = TiConvert.toString(options
					.get("shortDescription"));
		}
		if (options.containsKeyAndNotNull("amount")) {
			this.amount = new BigDecimal(TiConvert.toString(options
					.get("amount")));
		}
		if (options.containsKeyAndNotNull("tax")) {
			this.tax = new BigDecimal(TiConvert.toString(options.get("tax")));
		}
		if (options.containsKeyAndNotNull("shipping")) {
			this.shipping = new BigDecimal(TiConvert.toString(options
					.get("shipping")));
		}
		Log.d(LCAT, options.toString());
		if (options.containsKeyAndNotNull("items")) {
			Log.d(LCAT, "importing of items");
			List<Map<String, String>> paymentItems = new ArrayList<Map<String, String>>();
			Object items = options.get("items");
			if (!(items.getClass().isArray())) {
				throw new IllegalArgumentException("items must be an array");
			}
			Object[] itemArray = (Object[]) items;
			Log.d(LCAT, "is Object[]");
			for (int i = 0; i < itemArray.length; i++) {
				Log.d(LCAT, "" + i);
				Map<String, String> item = (Map<String, String>) itemArray[i];

				paymentItems.add(item);
			}
			Log.d(LCAT, "items imported");
		}
		if (options.containsKeyAndNotNull("configuration")) {
			KrollDict configurationDict = options.getKrollDict("configuration");
			if (!(configurationDict instanceof KrollDict)) {
				throw new IllegalArgumentException("Invalid argument type `"
						+ configurationDict.getClass().getName()
						+ "` passed to consume()");
			}
			ppConfiguration.environment(PaypalModule.CONFIG_ENVIRONMENT);
			if (configurationDict.containsKeyAndNotNull("merchantName")) {
				ppConfiguration.merchantName(configurationDict
						.getString("merchantName"));
			}
			if (configurationDict
					.containsKeyAndNotNull("merchantPrivacyPolicyURL")) {
				try {
					ppConfiguration.merchantPrivacyPolicyUri(Uri
							.parse(configurationDict
									.getString("merchantPrivacyPolicyURL")));
				} catch (NullPointerException e) {
				}
				try {
					ppConfiguration.merchantUserAgreementUri(Uri
							.parse(configurationDict
									.getString("merchantUserAgreementURL")));
				} catch (NullPointerException e) {
				}
			}
			ppConfiguration.clientId(PaypalModule.clientId);
			Log.d(LCAT, ppConfiguration.toString());
		}
	}

	private PayPalPayment getStuffToBuy(String paymentIntent) {
		if (paymentItems == null) {
			return new PayPalPayment(amount, currencyCode, shortDescription,
					paymentIntent);
		}
		/* iterating thrue all items from KrollDict: */
		PayPalItem[] items = new PayPalItem[this.paymentItems.size()];
		for (int i = 0; i < this.paymentItems.size(); i++) {
			String name = "", sku = "", currency = "EU";
			BigDecimal price = new BigDecimal(0);
			int quantify = 1;
			KrollDict paymentItem = paymentItems.get(i);
			if (paymentItem.containsKeyAndNotNull("name")) {
				name = TiConvert.toString(paymentItem.get("name"));
			}
			if (paymentItem.containsKeyAndNotNull("sku")) {
				sku = TiConvert.toString(paymentItem.get("sku"));
			}
			if (paymentItem.containsKeyAndNotNull("currency")) {
				currency = TiConvert.toString(paymentItem.get("currency"));
			}
			if (paymentItem.containsKeyAndNotNull("quantify")) {
				quantify = TiConvert.toInt(paymentItem.get("quantify"));
			}
			if (paymentItem.containsKeyAndNotNull("price")) {
				price = new BigDecimal(TiConvert.toString(paymentItem
						.get("price")));
			}
			items[i] = new PayPalItem(name, quantify, price, currency, sku);

		}
		BigDecimal subtotal = PayPalItem.getItemTotal(items);
		BigDecimal shipping = this.shipping;
		BigDecimal tax = this.tax;
		PayPalPaymentDetails paymentDetails = new PayPalPaymentDetails(
				shipping, subtotal, tax);
		BigDecimal amount = subtotal.add(shipping).add(tax);
		PayPalPayment payment = new PayPalPayment(amount, this.currencyCode,
				this.shortDescription, paymentIntent);
		payment.items(items).paymentDetails(paymentDetails);
		payment.custom("This is text that will be associated with the payment that the app can use.");
		return payment;
	}

	private void sendAuthorizationToServer(PayPalAuthorization authorization) {
	}

}