/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.paypal;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;
import android.support.v7.media.MediaRouter;

import com.paypal.android.sdk.payments.PayPalAuthorization;
import com.paypal.android.sdk.payments.PayPalConfiguration;
import com.paypal.android.sdk.payments.PayPalFuturePaymentActivity;
import com.paypal.android.sdk.payments.PayPalItem;
import com.paypal.android.sdk.payments.PayPalOAuthScopes;
import com.paypal.android.sdk.payments.PayPalPayment;
import com.paypal.android.sdk.payments.PayPalPaymentDetails;
import com.paypal.android.sdk.payments.PayPalProfileSharingActivity;
import com.paypal.android.sdk.payments.PayPalService;
import com.paypal.android.sdk.payments.PaymentActivity;
import com.paypal.android.sdk.payments.PaymentConfirmation;
import com.paypal.android.sdk.payments.ShippingAddress;

import java.math.BigDecimal;

// This proxy can be created by calling Paypal.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = PaypalModule.class)
public class PaymentItemProxy extends KrollProxy {
	// Standard Debugging variables
	private static final String LCAT = "Paypal_PaymentItem";
	String name;
	BigDecimal price;
	String sku;
	int quantity;
	String currency;
	// https://github.com/paypal/PayPal-Android-SDK
	private PayPalItem mPayPalItem;
	// Constructor
	public PaymentItemProxy() {
		super();
		new PayPalItem(name, quantity, price, currency,sku);
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict args) {
		super.handleCreationDict(args);
		if (args.containsKeyAndNotNull("name")) {
			name = TiConvert.toString(args.get("name"));
		} else
			Log.d(LCAT, "name is missing");
		if (args.containsKeyAndNotNull("price")) {
			price = new BigDecimal(TiConvert.toString(args.get("price")));
		} else
			Log.d(LCAT, "price is missing");
		if (args.containsKeyAndNotNull("sku")) {
			sku = TiConvert.toString(args.get("sku"));
		} else
			Log.d(LCAT, "sku is missing");
		if (args.containsKeyAndNotNull("quantity")) {
			quantity = TiConvert.toInt(args.get("quantity"));
		} else
			Log.d(LCAT, "quantity is missing");
		if (args.containsKeyAndNotNull("currency")) {
			currency = TiConvert.toString(args.get("currency"));
		} else
			Log.d(LCAT, "currency is missing");
	}
}